# Jay grammar
# Copyright (C) 2022  Loris Cuntreri

# Types

<int> ::= [0-9]+
<float> ::= [0-9]+ "." [0-9]+
<string> ::= "\"" ( ( [a-z]+ | [A-Z]+ )+ | ( [A-Z]+ | [a-z]+ )+ )+ "\""
<char> ::= "'" ( [a-z] | [A-Z] ) "'"

<type_def> ::= "int" | "float" | "char" | "string"

# Variables
<identifier> ::= ( [a-z]+ | [A-Z]+ )+ | ( [A-Z]+ | [a-z]+ )+

<var_def> ::= ( "let" | "var" | "const" ) " "
<var_decl> ::= <var_def>  <identifier> ":" <type_def> "=" ( <int> | <float> | <string> | <char> )
